os: linux
dist: trusty
language: php
php: 7.2

before_install:
  - composer install
  - npm install

script:
  # Validate the composer.json file.
  # @link https://getcomposer.org/doc/03-cli.md#validate
  - composer validate --no-check-all --strict

  # Lint the PHP files against parse errors.
  - composer lint

  # Check the code against the standards as documented in the phpcs.xml.dist file.
  - composer checkcs

  # Run the theme through lint:js checker as defined in @wordpress/scripts package.
  - npm run lint:js

  # Run the theme through lint:css checker as defined in @wordpress/scripts package.
  - npm run lint:css

  # Run the theme through lint:pkg-json checker as defined in @wordpress/scripts package.
  - npm run lint:pkg-json
